pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building ...'

                sh 'gradle bootJar'
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying ...'
            }
        }
    }
}