pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building ...'

                sh '''
                cd message-producer
                /opt/gradle/gradle-6.3/bin/gradle bootJar
                '''
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying ...'
            }
        }
    }
}