pipeline {
    agent any

    environment {
        subProjectPath = 'message-producer'
        artifactId = 'message-producer'
        version = '0.0.1-SNAPSHOT'
        jarFile = "${artifactId}-${version}.jar"
        groupId = 'th.co.bitfactory.testkafka'
    }

    stages {
        stage('Build') {
            steps {
                echo 'Building ...'

                sh '''
                cd $subProjectPath
                /opt/gradle/gradle-6.3/bin/gradle bootJar
                cd ..
                '''

                stash includes: "${env.subProjectPath}/build/libs/${env.jarFile}", name: 'jar-file'
            }
        }

        stage('Archive') {
            steps {
                unstash 'jar-file'

                sh '''
                cd $subProjectPath
                /opt/gradle/gradle-6.3/bin/gradle publish
                cd ..
                '''

                stash includes: "${env.subProjectPath}/build/libs/${env.jarFile}", name: 'jar-file'
            }
        }

        stage('Image') {
            steps {
                unstash 'jar-file'

                def testImage = docker.build("message-producer", "./message-producer/deployment/resources")
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying ...'
            }
        }
    }
}